Repository dbeattie/nag-me-api, pull requests merged in 2020-02, with the labels that each got.

#10 impliment multiple messages sent via twilio
  package-lock.json
  package.json
  src/index.js
Labels: bug

#11 setup cron job to send sms
  src/index.js
Labels: enhancement

#12 User auth
  package-lock.json
  package.json
  src/application.js
  src/index.js
  src/routes/auth.js
  src/routes/login.js
  src/routes/logout.js
  src/routes/register.js
Labels: enhancement

#13 Setup cron
  src/helpers/sendMessages.js
  src/index.js
Labels: enhancement

#17 phone numbers added to db
  src/db/schema/create.sql
  src/db/schema/development.sql
  src/db/schema/production.sql
  src/db/schema/test.sql
Labels: enhancement

#18 Incomplete nags going out
  src/db/schema/create.sql
  src/db/schema/development.sql
  src/db/schema/production.sql
  src/db/schema/test.sql
  src/helpers/grabsGoalIdWhenIncomplete.js
  src/helpers/sendMessages.js
  src/routes/nags.js
Labels: enhancement

#21 Send nags at diff times
  src/helpers/sendMessages.js
  src/routes/nags.js
Labels: enhancement

#23 clean up, only sending an SMS to one friend at the moment at the evening
  src/helpers/sendMessages.js
  src/routes/nags.js
Labels: help wanted

#28 add toggle true and toggle false logic
  src/routes/nags.js
Labels: enhancement

#32 Fix all queries
  src/db/schema/development.sql
  src/db/schema/production.sql
  src/db/schema/test.sql
  src/routes/goals.js
  src/routes/login.js
  src/routes/logout.js
  src/routes/nags.js
  src/routes/register.js
  src/routes/users.js
Labels: enhancement

#33 Delete nag onclick
  src/db/schema/development.sql
  src/db/schema/production.sql
  src/db/schema/test.sql
  src/routes/goals.js
  src/routes/nags.js
Labels: enhancement

#34 Fix delete query
  src/routes/goals.js
  src/routes/nags.js
Labels: bug

#35 create simple date columns on nag/goal routes
  src/routes/goals.js
  src/routes/nags.js
Labels: enhancement

#36 fixed goal/edit route
  src/routes/goals.js
Labels: bug

#37 handle query edge cases and update sms messages
  src/helpers/goalIdFind.js
  src/helpers/sendMessages.js
  src/routes/nags.js
Labels: bug

#38 cleaned out development seeds for presentation
  src/db/schema/development.sql
  src/db/schema/production.sql
  src/db/schema/test.sql
  src/routes/goals.js
  src/routes/nags.js
Labels: duplicate

#39 handles the problem of not being in london
  src/helpers/getTOTime.js
  src/helpers/sendMessages.js
  src/index.js
  src/routes/goals.js
Labels: bug

#40 Update sms message
  README.md
  src/application.js
  src/db/index.js
  src/helpers/getTOTime.js
  src/helpers/goalIdFind.js
  src/helpers/grabsGoalIdWhenIncomplete.js
  src/helpers/sendMessages.js
  src/index.js
  src/routes/goals.js
  src/routes/login.js
  src/routes/logout.js
  src/routes/nags.js
  src/routes/register.js
  src/routes/users.js
Labels: enhancement

#41 Update readme
  README.md
Labels: documentation
